#!/usr/bin/env python3
# catcomp.py - catalog tool for MDEdit (a small CatComp/FlexCat replacement)
#
# Copyright (c) 2026 André Gewert <agewert@ubergeek.de>, MIT License
#
#   catcomp.py header  <file.cd> <strings.h>
#   catcomp.py catalog <file.cd> <language.ct> <file.catalog>
#
# The .cd (catalog description, the built-in English strings) and .ct
# (translation) files use the format of CatComp and FlexCat, so those
# tools work on them as well:
#
#   .cd:  MSG_NAME (//)          .ct:  ## version $VER: X.catalog 1.0 (dd.mm.yyyy)
#         text                         ## codeset 0
#         ;                            ## language deutsch
#                                      MSG_NAME
#                                      Text
#                                      ; comment
#
# Lines starting with ';' are comments, a '\' at the end of a text line
# continues it. Escapes: \n \t \e \\ \" \xHH. The strings are numbered in
# the order of the .cd, starting at 0. A translation must use the same
# format specifiers (%s, %ld ...) in the same order; untranslated strings
# are left out of the catalog (locale.library uses the built-in ones).
#
# The catalog is an IFF FORM CTLG with FVER, LANG, CSET and STRS chunks;
# every string is stored as ID, length and the bytes, padded with NULs to
# 4 bytes. As in the catalogs of AmigaOS 3.2 (CatComp) the length counts
# the terminating NUL only if the padding would not add one ("Ja" 2,
# "Nein" 5).

import re, struct, sys

ESCAPES = {'n': '\n', 't': '\t', 'e': '\x1b', '\\': '\\', '"': '"', 'r': '\r', '0': '\0'}


def unescape(s):
    out, i = [], 0
    while i < len(s):
        c = s[i]
        if c == '\\' and i + 1 < len(s):
            n = s[i + 1]
            if n == 'x' and re.match(r'[0-9a-fA-F]{2}', s[i + 2:i + 4]):
                out.append(chr(int(s[i + 2:i + 4], 16)))
                i += 4
                continue
            if n in ESCAPES:
                out.append(ESCAPES[n])
                i += 2
                continue
        out.append(c)
        i += 1
    return ''.join(out)


def read_text(lines, i):
    """ text lines from lines[i] on, joined while they end with '\\' """
    text = ''
    while i < len(lines):
        l = lines[i]
        i += 1
        if l.endswith('\\') and not l.endswith('\\\\'):
            text += l[:-1]
            continue
        text += l
        break
    return unescape(text), i


def parse_cd(path):
    lines = open(path, encoding='latin-1').read().split('\n')
    entries, i = [], 0
    while i < len(lines):
        l = lines[i]
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*\(.*\)\s*$', l)
        i += 1
        if not m:
            continue
        text, i = read_text(lines, i)
        entries.append((m.group(1), text))
    names = [e[0] for e in entries]
    dup = {n for n in names if names.count(n) > 1}
    if dup:
        sys.exit('%s: duplicate names %s' % (path, ', '.join(sorted(dup))))
    return entries


def parse_ct(path):
    lines = open(path, encoding='latin-1').read().split('\n')
    head, strings, i = {}, {}, 0
    while i < len(lines):
        l = lines[i]
        i += 1
        if l.startswith('##'):
            parts = l[2:].strip().split(None, 1)
            if len(parts) == 2:
                head[parts[0].lower()] = parts[1]
            continue
        if not l or l.startswith(';'):
            continue
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*$', l)
        if not m:
            sys.exit('%s:%d: expected a string name: %r' % (path, i, l))
        text, i = read_text(lines, i)
        strings[m.group(1)] = text
    for k in ('version', 'language'):
        if k not in head:
            sys.exit('%s: "## %s" is missing' % (path, k))
    return head, strings


FORMAT = re.compile(r'%[-+ #0]*\d*(?:\.\d+)?[lh]?[diouxXcsp%]')


def specifiers(s):
    return [f[-1] + ('l' if 'l' in f else '') for f in FORMAT.findall(s) if f != '%%']


def c_string(s):
    out = '"'
    for ch in s.encode('latin-1'):
        c = chr(ch)
        if c == '"' or c == '\\':
            out += '\\' + c
        elif c == '\n':
            out += '\\n'
        elif 32 <= ch < 127:
            out += c
        else:
            out += '\\%03o' % ch
    return out + '"'


def header(cd, out):
    entries = parse_cd(cd)
    lines = ['/* %s - generated by tools/catcomp.py from %s, do not edit */' % (out.split('/')[-1], cd),
             '#ifndef STRINGS_H', '#define STRINGS_H', '']
    for n, (name, _) in enumerate(entries):
        lines.append('#define %-28s %d' % (name, n))
    lines += ['#define MSG_COUNT                    %d' % len(entries), '',
              '/* the built-in (English) strings, defined where MDEDIT_STRINGS is set */',
              '#ifdef MDEDIT_STRINGS',
              'static const char *const msg_builtin[MSG_COUNT] = {']
    for name, text in entries:
        lines.append('    %s,' % c_string(text))
    lines += ['};', '#endif', '', '#endif /* STRINGS_H */', '']
    open(out, 'w', encoding='latin-1', newline='\n').write('\n'.join(lines))


def chunk(cid, data):
    return cid + struct.pack('>I', len(data)) + data + (b'\0' if len(data) & 1 else b'')


def catalog(cd, ct, out):
    entries = parse_cd(cd)
    head, strings = parse_ct(ct)
    ids = {name: n for n, (name, _) in enumerate(entries)}
    errors = []
    for name in strings:
        if name not in ids:
            errors.append('%s: unknown string %s' % (ct, name))
    for name, text in entries:
        if name in strings and specifiers(strings[name]) != specifiers(text):
            errors.append('%s: %s: format specifiers %s, the original has %s'
                          % (ct, name, specifiers(strings[name]), specifiers(text)))
    if errors:
        sys.exit('\n'.join(errors))
    missing = [name for name, _ in entries if name not in strings]
    if missing:
        print('%s: %d strings untranslated: %s' % (ct, len(missing), ' '.join(missing)))

    strs = b''
    for name, _ in entries:
        if name in strings:
            s = strings[name].encode('latin-1')
            n = len(s) + 1 if len(s) % 4 == 0 else len(s)
            strs += struct.pack('>II', ids[name], n) + s + b'\0' * (-len(s) % 4 or 4)
    codeset = int(head.get('codeset', '0'))
    data = b'CTLG'
    data += chunk(b'FVER', head['version'].encode('latin-1') + b'\0')
    data += chunk(b'LANG', head['language'].encode('latin-1') + b'\0')
    data += chunk(b'CSET', struct.pack('>8I', codeset, 0, 0, 0, 0, 0, 0, 0))
    data += chunk(b'STRS', strs)
    open(out, 'wb').write(chunk(b'FORM', data))


def main():
    if len(sys.argv) == 4 and sys.argv[1] == 'header':
        header(sys.argv[2], sys.argv[3])
    elif len(sys.argv) == 5 and sys.argv[1] == 'catalog':
        catalog(sys.argv[2], sys.argv[3], sys.argv[4])
    else:
        sys.exit(__doc__ or 'usage: catcomp.py header|catalog ...')


if __name__ == '__main__':
    main()
