/* strings.h - generated by tools/catcomp.py from catalogs/Kickdown.cd, do not edit */
#ifndef STRINGS_H
#define STRINGS_H

#define MSG_MENU_PROJECT             0
#define MSG_MENU_NEW                 1
#define MSG_MENU_OPEN                2
#define MSG_MENU_SAVE                3
#define MSG_MENU_SAVEAS              4
#define MSG_MENU_EXPORT              5
#define MSG_MENU_SETTINGS            6
#define MSG_MENU_ICONIFY             7
#define MSG_MENU_ABOUT               8
#define MSG_MENU_QUIT                9
#define MSG_MENU_EDIT                10
#define MSG_MENU_CUT                 11
#define MSG_MENU_COPY                12
#define MSG_MENU_PASTE               13
#define MSG_MENU_UNDO                14
#define MSG_MENU_REDO                15
#define MSG_MENU_SELECTALL           16
#define MSG_MENU_FIND                17
#define MSG_MENU_FINDNEXT            18
#define MSG_MENU_HIGHLIGHT           19
#define MSG_MENU_LINENUMBERS         20
#define MSG_MENU_PREVIEW             21
#define MSG_MENU_REFRESH             22
#define MSG_MENU_AUTOREFRESH         23
#define MSG_MENU_SYNCSCROLL          24
#define MSG_MENU_COPYPREVIEW         25
#define MSG_TB_NEW                   26
#define MSG_TBH_NEW                  27
#define MSG_TB_OPEN                  28
#define MSG_TBH_OPEN                 29
#define MSG_TB_SAVE                  30
#define MSG_TBH_SAVE                 31
#define MSG_TB_SAVEAS                32
#define MSG_TBH_SAVEAS               33
#define MSG_TB_CUT                   34
#define MSG_TBH_CUT                  35
#define MSG_TB_COPY                  36
#define MSG_TBH_COPY                 37
#define MSG_TB_PASTE                 38
#define MSG_TBH_PASTE                39
#define MSG_TB_UNDO                  40
#define MSG_TBH_UNDO                 41
#define MSG_TB_REDO                  42
#define MSG_TBH_REDO                 43
#define MSG_TB_FIND                  44
#define MSG_TBH_FIND                 45
#define MSG_TB_REFRESH               46
#define MSG_TBH_REFRESH              47
#define MSG_TB_EXPORT                48
#define MSG_TBH_EXPORT               49
#define MSG_TB_SETTINGS              50
#define MSG_TBH_SETTINGS             51
#define MSG_TB_ABOUT                 52
#define MSG_TBH_ABOUT                53
#define MSG_UNTITLED                 54
#define MSG_MODIFIED                 55
#define MSG_POSITION                 56
#define MSG_OK                       57
#define MSG_LOADED                   58
#define MSG_NEW_DOCUMENT             59
#define MSG_SAVED                    60
#define MSG_EXPORTED                 61
#define MSG_LINK                     62
#define MSG_PREVIEW_COPIED           63
#define MSG_PREVIEW_NOSEL            64
#define MSG_NOMEM_PREVIEW            65
#define MSG_NOMEM_SAVE               66
#define MSG_NOMEM_CONVERT            67
#define MSG_REPLACE_CANCEL           68
#define MSG_FILE_EXISTS              69
#define MSG_SAVE_DISCARD_CANCEL      70
#define MSG_MODIFIED_ASK             71
#define MSG_SAVE_FAILED              72
#define MSG_OPEN_FAILED              73
#define MSG_WRITE_FAILED             74
#define MSG_REQ_OPEN                 75
#define MSG_REQ_SAVE                 76
#define MSG_REQ_EXPORT               77
#define MSG_ABOUT                    78
#define MSG_UNKNOWN_DIALECT          79
#define MSG_NO_TEMPLATE              80
#define MSG_FONTS_NEXT_START         81
#define MSG_SETTINGS_SAVED           82
#define MSG_SETTINGS_SAVE_FAILED     83
#define MSG_CLASS_MISSING            84
#define MSG_HTML_MISSING             85
#define MSG_NO_WINDOW                86
#define MSG_SET_TITLE                87
#define MSG_SET_EDITOR               88
#define MSG_SET_PREVIEW              89
#define MSG_SET_MARKDOWN             90
#define MSG_SET_COLOURS              91
#define MSG_SET_WINDOW               92
#define MSG_SET_HIGHLIGHT            93
#define MSG_SET_LINENUMBERS          94
#define MSG_SET_RENDERER             95
#define MSG_SET_RENDER_HTML          96
#define MSG_SET_RENDER_TTF           97
#define MSG_SET_FONTS                98
#define MSG_SET_FONTS_AUTO           99
#define MSG_SET_FONTSIZE             100
#define MSG_SET_FONTS_NOTE           101
#define MSG_SET_AUTOREFRESH          102
#define MSG_SET_SYNC                 103
#define MSG_SET_DIALECT              104
#define MSG_SET_CHARSET              105
#define MSG_SET_TEMPLATE             106
#define MSG_SET_TEMPLATE_TITLE       107
#define MSG_SET_BUILTIN              108
#define MSG_SET_COL_HEADING          109
#define MSG_SET_COL_CODE             110
#define MSG_SET_COL_QUOTE            111
#define MSG_SET_COL_MARKER           112
#define MSG_SET_COL_LINK             113
#define MSG_SET_COL_URL              114
#define MSG_SET_COL_HTML             115
#define MSG_SET_COLT_HEADING         116
#define MSG_SET_COLT_CODE            117
#define MSG_SET_COLT_QUOTE           118
#define MSG_SET_COLT_MARKER          119
#define MSG_SET_COLT_LINK            120
#define MSG_SET_COLT_URL             121
#define MSG_SET_COLT_HTML            122
#define MSG_SET_DEFCOLOURS           123
#define MSG_SET_WIDTH                124
#define MSG_SET_HEIGHT               125
#define MSG_SET_LEFT                 126
#define MSG_SET_TOP                  127
#define MSG_SET_WINDOW_NOTE          128
#define MSG_SET_CURRENT              129
#define MSG_SET_AUTOMATIC            130
#define MSG_SET_SAVE                 131
#define MSG_SET_USE                  132
#define MSG_SET_CANCEL               133
#define MSG_FIND_TITLE               134
#define MSG_FIND_FIND                135
#define MSG_FIND_WITH                136
#define MSG_FIND_CASE                137
#define MSG_FIND_WORDS               138
#define MSG_FIND_BACKWARDS           139
#define MSG_FIND_WRAP                140
#define MSG_FIND_DOFIND              141
#define MSG_FIND_REPLACE             142
#define MSG_FIND_REPLACEALL          143
#define MSG_FIND_CLOSE               144
#define MSG_FIND_NOTFOUND            145
#define MSG_FIND_ONE                 146
#define MSG_FIND_MANY                147
#define MSG_FIND_NOWINDOW            148
#define MSG_MENU_FORMAT              149
#define MSG_MENU_HEADING             150
#define MSG_MENU_BOLD                151
#define MSG_MENU_ITALIC              152
#define MSG_MENU_CODE                153
#define MSG_MENU_LINK                154
#define MSG_MENU_IMAGE               155
#define MSG_MENU_BULLET              156
#define MSG_MENU_NUMBERED            157
#define MSG_MENU_TASK                158
#define MSG_MENU_QUOTE               159
#define MSG_TBH_HEADING              160
#define MSG_TBH_BOLD                 161
#define MSG_TBH_ITALIC               162
#define MSG_TBH_CODE                 163
#define MSG_TBH_LINK                 164
#define MSG_TBH_IMAGE                165
#define MSG_TBH_BULLET               166
#define MSG_TBH_NUMBERED             167
#define MSG_TBH_TASK                 168
#define MSG_TBH_QUOTE                169
#define MSG_MENU_UNDERLINE           170
#define MSG_TBH_UNDERLINE            171
#define MSG_SET_TOOLBAR              172
#define MSG_SET_TBMODE               173
#define MSG_SET_TB_IMAGES            174
#define MSG_SET_TB_BOTH              175
#define MSG_SET_TB_TEXT              176
#define MSG_SET_TBFRAMES             177
#define MSG_SET_TOOLBAR_NOTE         178
#define MSG_TOOLBAR_NEXT_START       179
#define MSG_TB_HEADING               180
#define MSG_TB_BOLD                  181
#define MSG_TB_ITALIC                182
#define MSG_TB_UNDERLINE             183
#define MSG_TB_CODE                  184
#define MSG_TB_LINK                  185
#define MSG_TB_IMAGE                 186
#define MSG_TB_BULLET                187
#define MSG_TB_NUMBERED              188
#define MSG_TB_QUOTE                 189
#define MSG_TB_TASK                  190
#define MSG_MENU_FORMATBAR           191
#define MSG_SET_FMTBUTTONS           192
#define MSG_TBH_MORE                 193
#define MSG_SPLASH_SUBTITLE          194
#define MSG_SPLASH_VERSION           195
#define MSG_SPLASH_CLASSES           196
#define MSG_SPLASH_PREVIEW           197
#define MSG_SPLASH_IMAGES            198
#define MSG_SPLASH_TOOLBAR           199
#define MSG_SPLASH_WINDOW            200
#define MSG_SET_SPLASH               201
#define MSG_ABOUT_DETAILS            202
#define MSG_MENU_PRINT               203
#define MSG_TB_PRINT                 204
#define MSG_TBH_PRINT                205
#define MSG_PR_TITLE                 206
#define MSG_PR_OUTPUT                207
#define MSG_PR_PAGE                  208
#define MSG_PR_MODE                  209
#define MSG_PR_MODE_PRINTER          210
#define MSG_PR_DEST                  211
#define MSG_PR_DEST_FILE             212
#define MSG_PR_DEST_PRT              213
#define MSG_PR_DEST_PS               214
#define MSG_PR_DEST_DEVICE           215
#define MSG_PR_FILE                  216
#define MSG_PR_FILE_TITLE            217
#define MSG_PR_DEVICE                218
#define MSG_PR_FROM                  219
#define MSG_PR_TO                    220
#define MSG_PR_COPIES                221
#define MSG_PR_RANGE_NOTE            222
#define MSG_PR_PAPER                 223
#define MSG_PR_MARGINS               224
#define MSG_PR_LEFT                  225
#define MSG_PR_TOP                   226
#define MSG_PR_RIGHT                 227
#define MSG_PR_BOTTOM                228
#define MSG_PR_FONT                  229
#define MSG_PR_SANS                  230
#define MSG_PR_SERIF                 231
#define MSG_PR_SIZE                  232
#define MSG_PR_PAGENUMBERS           233
#define MSG_PR_BACKGROUNDS           234
#define MSG_PR_MARGIN_NOTE           235
#define MSG_PR_PRINT                 236
#define MSG_PR_CANCEL                237
#define MSG_PR_FOOTER                238
#define MSG_PR_WRITING               239
#define MSG_PR_PRINTING              240
#define MSG_PR_PRINTED               241
#define MSG_PR_WRITTEN               242
#define MSG_PR_STOPPED               243
#define MSG_PR_ERROR                 244
#define MSG_PR_NODEVICE              245
#define MSG_PR_NOPAGES               246
#define MSG_PR_NEEDGADGET            247
#define MSG_PR_PROGRESS_TITLE        248
#define MSG_PR_STOP                  249
#define MSG_PR_NOPS                  250
#define MSG_PR_CANNOT_OPEN           251
#define MSG_SET_FITIMAGES            252
#define MSG_SET_FITIMAGES_NOTE       253
#define MSG_PR_PRINTER               254
#define MSG_PR_UNIT                  255
#define MSG_PR_TURBOPRINT            256
#define MSG_COUNT                    257

/* the built-in (English) strings, defined where KICKDOWN_STRINGS is set */
#ifdef KICKDOWN_STRINGS
static const char *const msg_builtin[MSG_COUNT] = {
    "Project",
    "New",
    "Open...",
    "Save",
    "Save as...",
    "Export HTML...",
    "Settings...",
    "Iconify",
    "About...",
    "Quit",
    "Edit",
    "Cut",
    "Copy",
    "Paste",
    "Undo",
    "Redo",
    "Select all",
    "Find...",
    "Find next",
    "Syntax highlighting",
    "Line numbers",
    "Preview",
    "Refresh",
    "Auto refresh",
    "Synchronize scrolling",
    "Copy selection",
    "New",
    "Create a new document",
    "Open",
    "Open a Markdown file",
    "Save",
    "Save the Markdown file",
    "Save as",
    "Save the Markdown file under a new name",
    "Cut",
    "Cut the selection",
    "Copy",
    "Copy the selection",
    "Paste",
    "Paste from the clipboard",
    "Undo",
    "Undo the last change",
    "Redo",
    "Redo the last undone change",
    "Find",
    "Find and replace",
    "Refresh",
    "Refresh the HTML preview",
    "Export",
    "Export the document as HTML file",
    "Settings",
    "Settings",
    "About",
    "About Kickdown",
    "Untitled",
    " (modified)",
    "Line %lu, Col %lu",
    "OK",
    "%s (%lu bytes)",
    "New document",
    "Saved",
    "HTML exported",
    "Link: %s",
    "Preview selection copied to the clipboard",
    "Nothing selected in the preview",
    "Not enough memory for the preview",
    "Not enough memory to save the text.",
    "Not enough memory to convert the text.",
    "Replace|Cancel",
    "%s\nalready exists. Replace it?",
    "Save|Discard|Cancel",
    "%s has been modified.\nSave the changes?",
    "Could not save",
    "Could not open",
    "Could not write",
    "Open Markdown file",
    "Save Markdown file",
    "Export HTML file",
    "%s %s\nMarkdown editor with HTML preview\n\nCopyright (c) 2026 Andr\351 Gewert\nwww.ubergeek.de - agewert@ubergeek.de\nReleased under the MIT License\n\nMarkdown parser: %s\nPreview: %s %ld.%ld",
    "Unknown dialect \"%s\", using GitHub.",
    "Could not read the template %s.",
    "Renderer and fonts take effect at the next start",
    "Settings saved",
    "Could not save the settings to",
    "Could not open %s.",
    "%s not found (SYS:Classes/Gadgets/ or program directory).",
    "Could not open the window.",
    "Kickdown settings",
    "Editor",
    "Preview",
    "Markdown",
    "Colours",
    "Window",
    "Syntax _highlighting",
    "Line _numbers",
    "R_enderer ",
    "html.gadget (bitmap fonts)",
    "htmlttf.gadget (TrueType)",
    "_TrueType fonts ",
    "Automatic",
    "_Font size (0 = auto) ",
    "Renderer and fonts take effect at the next start.",
    "_Refresh while typing",
    "S_ynchronize scrolling",
    "_Dialect ",
    "C_harset (empty = detect) ",
    "Page _template ",
    "Page template",
    "Built-_in",
    "_Headings ",
    "Co_de ",
    "_Quotes ",
    "Mar_kers, rules ",
    "_Links ",
    "U_RLs ",
    "HT_ML ",
    "Headings",
    "Code",
    "Quotes",
    "Markers and rules",
    "Links",
    "URLs",
    "HTML",
    "Default c_olours",
    "_Width (0 = auto) ",
    "H_eight (0 = auto) ",
    "_Left (-1 = centred) ",
    "_Top (-1 = centred) ",
    "Size and position of the main window at the next start.",
    "Cu_rrent",
    "_Automatic",
    "_Save",
    "_Use",
    "_Cancel",
    "Find and replace",
    "_Find ",
    "Replace _with ",
    "_Case sensitive",
    "Whole wor_ds",
    "_Backwards",
    "Wrap _around",
    "Fi_nd",
    "_Replace",
    "Replace a_ll",
    "Cl_ose",
    "\"%s\" not found",
    "1 replacement",
    "%lu replacements",
    "Could not create the find window",
    "Format",
    "Heading",
    "Bold",
    "Italic",
    "Code",
    "Link",
    "Image",
    "Bulleted list",
    "Numbered list",
    "Task list",
    "Quote",
    "Heading (#, every click one level more, up to ###)",
    "Bold (**text**)",
    "Italic (*text*)",
    "Code (`code`, several lines as code block)",
    "Link ([text](address))",
    "Image (![description](file))",
    "Bulleted list (- )",
    "Numbered list (1. )",
    "Task list (- [ ] )",
    "Quote (> )",
    "Underline",
    "Underline (<u>text</u>)",
    "Toolbar",
    "_Display ",
    "Images",
    "Images and text",
    "Text",
    "_Frames around the buttons",
    "Display and frames take effect at the next start.\nText only starts faster, no images are loaded.\nWith texts the formatting buttons get a second row.",
    "The toolbar changes at the next start",
    "Heading",
    "Bold",
    "Italic",
    "Underline",
    "Code",
    "Link",
    "Image",
    "List",
    "Numbered",
    "Quote",
    "Tasks",
    "Show formatting buttons",
    "Show f_ormatting buttons",
    "Buttons that do not fit",
    "Markdown editor with HTML preview",
    "Version %s",
    "Opening the ReAction classes...",
    "Opening the HTML preview...",
    "Loading the toolbar images...",
    "Preparing the toolbar...",
    "Opening the window...",
    "Show s_plash window at the start",
    "www.ubergeek.de - agewert@ubergeek.de\nReleased under the MIT License\n\nMarkdown parser: %s\nPreview: %s %ld.%ld",
    "Print...",
    "Print",
    "Print, also as PostScript or PDF",
    "Print",
    "Output",
    "Page",
    "_Type ",
    "Printer (graphics)",
    "_Destination ",
    "File",
    "PRT:",
    "PS: (TurboPrint)",
    "Device",
    "_File ",
    "Save as PostScript or PDF",
    "De_vice ",
    "Pages fro_m ",
    "t_o ",
    "Cop_ies ",
    "\"to\" 0 = up to the last page.",
    "Pape_r ",
    "Margins (mm) ",
    "left ",
    "top ",
    "right ",
    "bottom ",
    "Fo_nt ",
    "Sans serif (Helvetica)",
    "Serif (Times)",
    "_Size (pt) ",
    "Page n_umbers",
    "_Background colours",
    "The printer adds its own margins (often 3-5 mm).\nThe font is used for PostScript and PDF; the printer\noutput uses the fonts of the preview.",
    "_Print",
    "_Cancel",
    "Page %p of %n",
    "Writing page %ld of %ld",
    "Printing page %ld of %ld",
    "%ld pages printed",
    "%ld pages written to %s",
    "Printing stopped",
    "Printer error %ld",
    "printer.device cannot be opened.",
    "The document cannot be prepared for printing.",
    "Printing needs html.gadget or htmlttf.gadget 1.2 or newer.",
    "Printing",
    "_Stop",
    "PS: is not available (TurboPrint is not installed or not running).",
    "Cannot open the output",
    "Fit _big pictures to the preview width",
    "Scaling big pictures takes time on slower Amigas.",
    "Print_er ",
    "Unit %ld",
    "With TurboPrint, Kickdown prints through PostScript:\nchoose PostScript and PS: as destination.",
};
#endif

#endif /* STRINGS_H */
